client:
  image: gantagouthamyadav/fullstack-server:a910b25
  replicas: 2
  port: 3000

server:
  image: gantagouthamyadav/fullstack-server:a910b25
  replicas: 2
  port: 6001
  mongo:
    uri: "mongodb://fullstack-app-mongo.fullstack.svc.cluster.local:27017/mern-social"

ingress:
  enabled: true
  host: your-app.dev
