apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}-server
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      containers:
        - name: server
          image: {{ .Values.server.image }}
          ports:
            - containerPort: {{ .Values.server.port }}
          env:
            - name: MONGO_URI
              value: "{{ .Values.server.mongo.uri }}"
            - name: MONGODB_URI
              value: "{{ .Values.server.mongo.uri }}"
            - name: DB_URI
              value: "{{ .Values.server.mongo.uri }}"
         
